language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

matrix:
  include:
    - python: 2.6
      env: MOCK=mock==1.0.1
    - python: 2.7
      env: MOCK=mock

before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-pygame
  - sudo apt-get install -qq python-pygame

install:
  - pip install --use-mirrors -q nose
  - '[ -n "$MOCK" ] && pip install --use-mirrors -q $MOCK'

script:
    - nosetests tests/*.py