language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-pygame

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install mock; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install mock; fi
  - pip install pygame --allow-external pygame --allow-unverified pygame
  - pip install nose

script:
    - nosetests tests/*.py