language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install mock; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then pip install mock; fi
  - pip install nose coverage codecov

script:
  - coverage run --source=slumber --omit='*/cli.py' `which nosetests` tests/*.py

after_success:
  - codecov